### ISSUE TITLE
Dream Runner download function

### ISSUE THREAD

**Issue by kellrott** [Sage-Bionetworks/SMC-RNA-Challenge#15]
Dream runner should be able to automate the download of the training data.

**Comment by thomasyu888** [comment]
Would this be different from 

```
dream_runner.py --test isoform_quantification sim1 my_cwl_workflow.cwl
```

Would we add something like this:

```
dream_runner.py download dry_run_30m #That would download a specific training data set along with the associated truth file?
```

Or should it just be 

```
dream_runner --downloadTraining #download all the training files
```

**Comment by kellrott** [comment]
Lets go with sub-commands:
- download
- test
- generate ( print out an input json, without running )

**Comment by thomasyu888** [comment]
Download function:
https://github.com/Sage-Bionetworks/SMC-RNA-Challenge/blob/master/script/dream_runner.py#L83

The generate function will have the same issue as I posted about here: https://github.com/Sage-Bionetworks/SMC-RNA-Challenge/issues/20
