### ISSUE TITLE
Avoid hard coded paths

### ISSUE THREAD

**Issue by kellrott** [Sage-Bionetworks/SMC-RNA-Challenge#17]
We should avoid using hard coded paths, such as 

```
        val = subprocess.check_call(["/opt/SMC-RNA-Challenge/FusionDetection/Validator/bedpeValidatorS.py", "-c", "/opt/SMC-RNA-Challenge/FusionDetection/Validator/GRCh37.chromosome.strict.txt", "-i",args.input])
```

(found at https://github.com/Sage-Bionetworks/SMC-RNA-Challenge/blob/master/script/evaluation.py#L10)

Instead, use the python variable `__file__` to get the path of the file being run, and then work on the absolute path based on that. For example

```
validator_path = os.path.join( os.path.dirname(__file__), "..", "FusionDetection", "Validator", "bedpeValidatorS.py" )
```

**Comment by kellrott** [comment]
This goes for https://github.com/Sage-Bionetworks/SMC-RNA-Challenge/blob/master/script/dream_runner.py#L84 as well

**Comment by thomasyu888** [comment]
Add /opt/SMC-RNA-Challenge/scripts to path in docker

**Comment by thomasyu888** [comment]
Updated
