### ISSUE TITLE
Add link to synoptic quiz in validation email

### ISSUE THREAD

**Issue by kellrott** [Sage-Bionetworks/SMC-RNA-Challenge#19]
Add link to synoptic quiz on the message at https://github.com/Sage-Bionetworks/SMC-RNA-Challenge/blob/master/challenge/messages.py#L49 once the form URL is avalible.

**Comment by thomasyu888** [comment]
Updated: https://github.com/Sage-Bionetworks/SMC-RNA-Challenge/blob/master/challenge/messages.py#L57
