### ISSUE TITLE
Reorganize dream-smc-rna bucket

### ISSUE THREAD

**Issue by kellrott** [Sage-Bionetworks/SMC-RNA-Challenge#22]
The paths to elements in the dream-smc-rna bucket are unpredictable.
For example sim1 files are under dream-smc-rna/round1-75m/sim1_\* while the sim2 files are under dream-smc-rna/round1-50m/sim2_*
File paths should be predictable using only the base name of the files. 
Maybe put all of the files into the directory 'training' so all the paths would be in the form of dream-smc-rna/training/simX_XXXXX

**Comment by kkdang** [comment]
True, they are not predictable but they are informative for the users because the path indicates the depth of sequencing for the datasets. This information can be provided instead in a table. So I would say to go ahead with the reorg if it makes things easier for challenge execution.

**Comment by kellrott** [comment]
Everything has now been moved into the training folder.
